# Generated by Django 4.2.2 on 2023-06-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('declaration', models.TextField(blank=True, verbose_name='Опис')),
                ('add_datetime', models.DateTimeField(verbose_name='Час')),
                ('aim_type', models.CharField(choices=[('ціль', 'Objective'), ('задача', 'Task')], max_length=6, verbose_name='Тип')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
                ('status', models.CharField(choices=[('in progress', 'Inprogress'), ('done', 'Done')], max_length=11, verbose_name='Cтатус')),
                ('external_id', models.IntegerField()),
            ],
        ),
    ]
