# Generated by Django 4.2.2 on 2023-06-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aim',
            name='aim_type',
        ),
    ]
