# Generated by Django 4.2.2 on 2023-06-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_aim_aim_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aim',
            name='add_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Початок цілі'),
        ),
    ]
