# Generated by Django 4.2.2 on 2023-06-12 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_aim_add_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_datetime1', models.DateTimeField(verbose_name='Час нагадування 1')),
                ('notification_datetime2', models.DateTimeField(blank=True, verbose_name='Час нагадування 2')),
                ('notification_datetime3', models.DateTimeField(blank=True, verbose_name='Час нагадування 3')),
                ('notified_times', models.IntegerField(default=0, verbose_name='Вже повідомлено разів')),
                ('aim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.aim', verbose_name='Ціль')),
            ],
        ),
    ]
