# Generated by Django 4.2.2 on 2023-06-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
