# Generated by Django 4.2.2 on 2023-06-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='aim',
            name='times_notified',
            field=models.IntegerField(default=3, verbose_name='Стільки разів нагадати'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
