# Generated by Django 4.2.2 on 2023-06-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aim',
            name='times_notified',
        ),
    ]
